"""Reporting endpoints built from processed analytical tables.

Every export is generated by Python from the same processed tables the dashboard
uses, so a downloaded file always matches what the interface shows. CSV only for
now; PDF can be layered on later.
"""

from __future__ import annotations

import io

import pandas as pd
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import StreamingResponse

from app.repositories import dataset_repository as repo
from app.schemas.common import Provenance
from app.schemas.filters import AnalyticsFilters, analytics_filters
from app.services import analytics_service, dataset_service, postharvest_service

router = APIRouter(prefix="/reports", tags=["reports"])


def _csv_response(df: pd.DataFrame, filename: str) -> StreamingResponse:
    buffer = io.StringIO()
    df.to_csv(buffer, index=False)
    buffer.seek(0)
    return StreamingResponse(
        iter([buffer.getvalue()]),
        media_type="text/csv",
        headers={"Content-Disposition": f'attachment; filename="{filename}"'},
    )


@router.get("/district-summary")
def district_summary(district: str) -> dict:
    df = repo.training_dataset()
    sub = df[df["district"].astype(str).str.lower() == district.lower()]
    if sub.empty:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"no data for district: {district}")

    valid = sub[sub["yield_kg_ha"].fillna(0) > 0]
    by_crop = (
        valid.groupby("canonical_crop_name")
        .agg(
            crop_yield_median_kg_ha=("yield_kg_ha", "median"),
            production_mt=("production_mt", "sum"),
            harvested_area_ha=("harvested_area_ha", "sum"),
        )
        .reset_index()
        .rename(columns={"canonical_crop_name": "crop"})
    )
    by_crop = by_crop.where(pd.notna(by_crop), None)
    return {
        "district": district,
        "crops": by_crop.to_dict(orient="records"),
        "provenance": Provenance(
            source_id="NISR_SAS_2025B_DISTRICT_CROP",
            source_period="2025-B",
            method="aggregation of processed district x crop table",
            limitations=["district aggregates; within-district variation is not shown"],
        ).model_dump(),
    }


@router.get("/crop-summary")
def crop_summary(crop: str) -> dict:
    df = repo.training_dataset()
    sub = df[df["canonical_crop_name"].astype(str).str.lower() == crop.lower()]
    if sub.empty:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"no data for crop: {crop}")
    valid = sub[sub["yield_kg_ha"].fillna(0) > 0]
    g = analytics_service.gapped(sub, "national_crop_median")
    return {
        "crop": crop,
        "districts": int(valid["district"].nunique()),
        "median_yield_kg_ha": None if valid.empty else round(float(valid["yield_kg_ha"].median()), 1),
        "total_production_mt": None if valid.empty else round(float(valid["production_mt"].sum()), 1),
        "median_gap_index": None if g.empty else round(float(g["gap_index"].median()), 2),
        "provenance": Provenance(
            source_id="NISR_SAS_2025B_DISTRICT_CROP",
            source_period="2025-B",
            method="crop-level aggregation with national crop median benchmark",
            limitations=["district aggregates only", "association, not causation"],
        ).model_dump(),
    }


@router.get("/productivity-gap.csv")
def productivity_gap_csv(
    limit: int = 500, f: AnalyticsFilters = Depends(analytics_filters)
) -> StreamingResponse:
    df = analytics_service.gapped(
        analytics_service.apply_filters(repo.training_dataset(), f), f.benchmark_strategy
    )
    df = df[df["gap_index"].notna()].sort_values("gap_index", ascending=False).head(limit)
    columns = [
        "year", "season", "district", "district_code", "province", "canonical_crop_name",
        "cultivated_area_ha", "harvested_area_ha", "production_mt", "yield_kg_ha",
        "benchmark_yield_kg_ha", "gap_index", "benchmark_strategy",
    ]
    return _csv_response(
        df[[c for c in columns if c in df.columns]].rename(
            columns={"canonical_crop_name": "crop"}
        ),
        "productivity_gap.csv",
    )


@router.get("/intervention-priority.csv")
def intervention_priority_csv(
    limit: int = 500, f: AnalyticsFilters = Depends(analytics_filters)
) -> StreamingResponse:
    result = analytics_service.priorities(limit=limit, f=f)
    return _csv_response(pd.DataFrame(result["rows"]), "intervention_priority.csv")


@router.get("/post-harvest.csv")
def post_harvest_csv() -> StreamingResponse:
    result = postharvest_service.summary()
    return _csv_response(pd.DataFrame(result["crops"]), "post_harvest_use.csv")


@router.get("/dataset/{key}.csv")
def dataset_csv(key: str) -> StreamingResponse:
    """Export any whitelisted processed dataset exactly as the API serves it."""
    try:
        df = dataset_service.records_for_export(key)
    except KeyError:
        raise HTTPException(status.HTTP_404_NOT_FOUND, f"unknown dataset: {key!r}") from None
    return _csv_response(df, f"{key}.csv")
