@echo off
setlocal EnableDelayedExpansion

REM ============================================================================
REM Cropmatics Rwanda - build a shareable Android APK on Windows.
REM
REM Usage (from a terminal, or double-click this file):
REM   scripts\build-apk.bat                 API = this PC's LAN IP (demo mode)
REM   scripts\build-apk.bat --api URL       API = an explicit URL (deployed API)
REM   scripts\build-apk.bat --web URL       install landing page URL (QR target)
REM
REM Requirements:
REM   Node 20+, `pnpm install` done, eas-cli installed (npm i -g eas-cli),
REM   and logged in with: eas login   (a free Expo account)
REM
REM The first build takes ~10-20 minutes. Afterwards EAS hosts the .apk at a
REM public link; share that link, or the /install web page printed at the end.
REM ============================================================================

set "API_PORT=8000"
set "WEB_PORT=3000"
set "PROFILE=preview"
set "API_URL="
set "WEB_URL="

:parse
if "%~1"=="" goto parsed
if /i "%~1"=="--api" (
  set "API_URL=%~2"
  shift
  shift
  goto parse
)
if /i "%~1"=="--web" (
  set "WEB_URL=%~2"
  shift
  shift
  goto parse
)
echo Unknown option: %~1
echo Usage: build-apk.bat [--api URL] [--web URL]
exit /b 1
:parsed

REM ---- Detect this PC's LAN IP so phones on the same Wi-Fi can reach the API -
set "LAN_IP="
for /f "usebackq delims=" %%i in (`powershell -NoProfile -Command "(Get-NetIPAddress -AddressFamily IPv4 | Where-Object { $_.IPAddress -notlike '127.*' -and $_.IPAddress -notlike '169.254.*' } | Select-Object -First 1).IPAddress"`) do set "LAN_IP=%%i"
if "!LAN_IP!"=="" set "LAN_IP=127.0.0.1"

if "%API_URL%"=="" set "API_URL=http://!LAN_IP!:!API_PORT!/api/v1"
if "%WEB_URL%"=="" set "WEB_URL=http://!LAN_IP!:!WEB_PORT!/install"

echo API base URL : %API_URL%
echo Install page : %WEB_URL%
echo EAS profile  : %PROFILE%
echo.

REM ---- eas-cli present? -------------------------------------------------------
where eas >nul 2>&1
if errorlevel 1 (
  echo eas-cli not found. Install it with:  npm i -g eas-cli
  echo Then log in with:                    eas login
  pause
  exit /b 1
)

REM ---- Write apps\mobile\.env (values are baked into the APK at build time) --
set "MOB_DIR=%~dp0..\apps\mobile"
set "HAD_ENV=0"
if exist "%MOB_DIR%\.env" (
  copy /y "%MOB_DIR%\.env" "%MOB_DIR%\.env.build-backup" >nul
  set "HAD_ENV=1"
)
> "%MOB_DIR%\.env" (
  echo # Generated by scripts\build-apk.bat - values baked into the APK at build time.
  echo EXPO_PUBLIC_API_BASE_URL=%API_URL%
  echo EXPO_PUBLIC_INSTALL_PAGE_URL=%WEB_URL%
)

REM ---- Build ------------------------------------------------------------------
pushd "%MOB_DIR%"
call eas build --platform android --profile %PROFILE% --non-interactive
set "RC=%errorlevel%"
call :restore_env
popd

if not "%RC%"=="0" (
  echo.
  echo Build failed. Re-run after fixing the error above.
  pause
  exit /b %RC%
)

echo.
echo Build submitted. When it finishes, EAS shows a public link to the APK.
echo Share the /install page below - its QR code is what people scan:
echo    Install page : %WEB_URL%
echo    API base URL : %API_URL%
echo.
pause
exit /b 0

REM ---- Restore the developer .env that was backed up before the build --------
:restore_env
if "%HAD_ENV%"=="1" (
  if exist "%MOB_DIR%\.env.build-backup" (
    copy /y "%MOB_DIR%\.env.build-backup" "%MOB_DIR%\.env" >nul
    del "%MOB_DIR%\.env.build-backup"
  )
) else (
  if exist "%MOB_DIR%\.env" del "%MOB_DIR%\.env"
)
exit /b 0
