#!/usr/bin/env bash
#
# Build a shareable Android APK with EAS and print the QR/link to distribute.
#
# Usage:
#   ./scripts/build-apk.sh              # API = this machine's LAN IP (demo mode)
#   ./scripts/build-apk.sh --api URL    # API = an explicit URL (e.g. deployed API)
#   ./scripts/build-apk.sh --web URL    # install landing page URL (QR target)
#
# Requirements: an Expo account (free) and `eas-cli` (npm i -g eas-cli).
# The first build takes ~10-20 minutes; EAS hosts the .apk at a public URL
# afterwards. The QR/link shown at the end is what you share.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

PROFILE="preview"
API_URL=""
WEB_URL=""

while [ $# -gt 0 ]; do
  case "$1" in
    --api) API_URL="$2"; shift 2 ;;
    --web) WEB_URL="$2"; shift 2 ;;
    *) echo "unknown option: $1 (use --api URL and/or --web URL)"; exit 1 ;;
  esac
done

lan_ip() {
  local ip
  for iface in en0 en1 en2; do
    ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
    [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  done
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')" || true
  [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  printf '127.0.0.1'
}

API_PORT="${API_PORT:-8000}"
WEB_PORT="${WEB_PORT:-3000}"
IP="$(lan_ip)"

# ---- resolve config ---------------------------------------------------------
API_FINAL="${API_URL:-http://$IP:$API_PORT/api/v1}"
WEB_FINAL="${WEB_URL:-http://$IP:$WEB_PORT/install}"

ENV_FILE="apps/mobile/.env.build"
cat > "$ENV_FILE" <<EOF
# Generated by scripts/build-apk.sh — values baked into the APK at build time.
EXPO_PUBLIC_API_BASE_URL=$API_FINAL
EXPO_PUBLIC_INSTALL_PAGE_URL=$WEB_FINAL
EOF

echo "==> API base URL   : $API_FINAL"
echo "==> Install page   : $WEB_FINAL"
echo "==> EAS profile    : $PROFILE"
echo

# eas-cli reads apps/mobile/.env* files. Point it at the generated file.
export EAS_NO_VCS=1
cd apps/mobile

# eas-cli picks up .env files in precedence order; move any local .env aside so
# the build-time values win. (Only inside this script; restored on exit.)
restore_env() {
  [ -f .env ] && mv .env .env.build-backup
  [ -f "$ENV_FILE_BACKUP" ] && mv "$ENV_FILE_BACKUP" .env || true
  rm -f .env.build
}
ENV_FILE_BACKUP=""
if [ -f .env ]; then
  mv .env .env.build-backup
  ENV_FILE_BACKUP=".env.build-backup"
fi
trap restore_env EXIT

mv "$ENV_FILE" .env

# ---- build ------------------------------------------------------------------
if ! command -v eas >/dev/null 2>&1; then
  echo "eas-cli not found. Install it with: npm i -g eas-cli"
  echo "Then log in:        eas login"
  exit 1
fi

eas build --platform android --profile "$PROFILE" --non-interactive

# ---- done -------------------------------------------------------------------
cat <<EOF

Build submitted. When it finishes (10-20 min) EAS shows a public link to the
APK. Share that link — or the /install page below, which carries the QR code:

  Install page : $WEB_FINAL
  API base URL : $API_FINAL

Print/present the /install page on the big screen: its QR is what people scan.
EOF
