#!/usr/bin/env bash
#
# Build a shareable Android APK with EAS and print the QR/link to distribute.
#
# Usage:
#   ./scripts/build-apk.sh              # API = this machine's LAN IP (demo mode)
#   ./scripts/build-apk.sh --api URL    # API = an explicit URL (e.g. deployed API)
#   ./scripts/build-apk.sh --web URL    # install landing page URL (QR target)
#
# Requirements: an Expo account (free) and `eas-cli` (npm i -g eas-cli, then
# `eas login`). The first build takes ~10-20 minutes; EAS hosts the .apk at a
# public URL afterwards. The /install page printed at the end is what you share.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MOBILE_DIR="$ROOT/apps/mobile"

PROFILE="preview"
API_URL=""
WEB_URL=""

while [ $# -gt 0 ]; do
  case "$1" in
    --api) API_URL="$2"; shift 2 ;;
    --web) WEB_URL="$2"; shift 2 ;;
    *) echo "unknown option: $1 (use --api URL and/or --web URL)"; exit 1 ;;
  esac
done

lan_ip() {
  local ip
  for iface in en0 en1 en2; do
    ip="$(ipconfig getifaddr "$iface" 2>/dev/null || true)"
    [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  done
  ip="$(hostname -I 2>/dev/null | awk '{print $1}')" || true
  [ -n "$ip" ] && { printf '%s' "$ip"; return 0; }
  printf '127.0.0.1'
}

API_PORT="${API_PORT:-8000}"
WEB_PORT="${WEB_PORT:-3000}"
IP="$(lan_ip)"

# ---- resolve config ---------------------------------------------------------
API_FINAL="${API_URL:-http://$IP:$API_PORT/api/v1}"
WEB_FINAL="${WEB_URL:-http://$IP:$WEB_PORT/install}"

echo "==> API base URL   : $API_FINAL"
echo "==> Install page   : $WEB_FINAL"
echo "==> EAS profile    : $PROFILE"
echo

if ! command -v eas >/dev/null 2>&1; then
  echo "eas-cli not found. Install it with:  npm i -g eas-cli"
  echo "Then log in with:                    eas login"
  exit 1
fi

# ---- bake build-time env ----------------------------------------------------
# eas-cli reads apps/mobile/.env* at build time and Expo inlines EXPO_PUBLIC_*
# values into the bundle, so the APK talks to the chosen API forever after.
# The developer's own .env is backed up and restored on exit.
GEN_ENV="$MOBILE_DIR/.env"
BACKUP_ENV="$MOBILE_DIR/.env.build-backup"

HAD_DEV_ENV=0
[ -f "$GEN_ENV" ] && { cp "$GEN_ENV" "$BACKUP_ENV"; HAD_DEV_ENV=1; }

restore_env() {
  rm -f "$GEN_ENV"
  [ "$HAD_DEV_ENV" = "1" ] && mv "$BACKUP_ENV" "$GEN_ENV"
  return 0
}
trap restore_env EXIT

cat > "$GEN_ENV" <<EOF
# Generated by scripts/build-apk.sh — values baked into the APK at build time.
EXPO_PUBLIC_API_BASE_URL=$API_FINAL
EXPO_PUBLIC_INSTALL_PAGE_URL=$WEB_FINAL
EOF

# ---- build ------------------------------------------------------------------
cd "$MOBILE_DIR"
eas build --platform android --profile "$PROFILE" --non-interactive

# ---- done -------------------------------------------------------------------
cat <<EOF

Build submitted. When it finishes (10-20 min) EAS shows a public link to the
APK. Share that link — or the /install page below, which carries the QR code:

  Install page : $WEB_FINAL
  API base URL : $API_FINAL

Present the /install page on the big screen: its QR is what people scan.
EOF
