"""initial schema

Revision ID: 4c12c6b6c457
Revises:
Create Date: 2026-09-25 20:22:07.187612

Hand-edited after autogenerate for three reasons:

1. ``geoalchemy2`` is imported: the geometry columns reference
   ``geoalchemy2.types.Geometry``, which autogenerate emits without the import.
2. ``CREATE EXTENSION IF NOT EXISTS postgis`` runs first, so a fresh database
   (Neon, Supabase) needs no manual setup before ``upgrade head``.
3. The autogenerated ``drop_table('spatial_ref_sys')`` / ``create_table(...)``
   pair was removed. ``spatial_ref_sys`` belongs to PostGIS and is created by the
   extension, not by this application. Dropping it would break every geometry
   column.
"""

from __future__ import annotations

from alembic import op
import geoalchemy2  # noqa: F401  (referenced by the geometry columns below)
import sqlalchemy as sa


revision = '4c12c6b6c457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # PostGIS is required by the geometry columns in this migration. Creating it
    # here keeps `alembic upgrade head` a single, self-contained step.
    op.execute("CREATE EXTENSION IF NOT EXISTS postgis")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('full_name', sa.String(length=160), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('preferred_language', sa.String(length=8), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_user_email')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=False)
    op.create_table('crop',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('name_kinyarwanda', sa.String(length=64), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('perishability', sa.String(length=16), nullable=True),
    sa.Column('cold_chain_recommended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crop_code'), 'crop', ['code'], unique=True)
    op.create_index(op.f('ix_crop_name'), 'crop', ['name'], unique=True)
    op.create_table('data_source',
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('owner', sa.String(length=96), nullable=True),
    sa.Column('dataset_name', sa.String(length=160), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(length=48), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('access_type', sa.String(length=48), nullable=True),
    sa.Column('license_or_terms', sa.String(), nullable=True),
    sa.Column('raw_file', sa.String(), nullable=True),
    sa.Column('processing_script', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_source_source_id'), 'data_source', ['source_id'], unique=True)
    op.create_table('model_version',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('metrics', sa.String(), nullable=True),
    sa.Column('artifact_path', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_model_version')
    )
    op.create_index(op.f('ix_model_version_name'), 'model_version', ['name'], unique=False)
    op.create_table('province',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_province_code'), 'province', ['code'], unique=True)
    op.create_table('recommendation',
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('recommendation_type', sa.String(length=32), nullable=True),
    sa.Column('text_en', sa.String(), nullable=True),
    sa.Column('text_rw', sa.String(), nullable=True),
    sa.Column('evidence', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendation_target_id'), 'recommendation', ['target_id'], unique=False)
    op.create_table('role',
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_name'), 'role', ['name'], unique=True)
    op.create_table('audit_log',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=True),
    sa.Column('target_type', sa.String(length=48), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_actor_id'), 'audit_log', ['actor_id'], unique=False)
    op.create_table('district',
    sa.Column('code', sa.String(length=16), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('province_id', sa.Uuid(), nullable=False),
    sa.Column('agro_ecological_zone', sa.String(length=64), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['province_id'], ['province.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_district_name')
    )
    op.create_index('idx_district_geometry', 'district', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_district_code'), 'district', ['code'], unique=True)
    op.create_index(op.f('ix_district_name'), 'district', ['name'], unique=False)
    op.create_index(op.f('ix_district_province_id'), 'district', ['province_id'], unique=False)
    op.create_table('notification',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('channel', sa.String(length=16), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('sync_event',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.String(length=48), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('server_id', sa.Uuid(), nullable=True),
    sa.Column('operation', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_event_client_uuid'), 'sync_event', ['client_uuid'], unique=False)
    op.create_index(op.f('ix_sync_event_user_id'), 'sync_event', ['user_id'], unique=False)
    op.create_table('user_role',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_user_role')
    )
    op.create_index(op.f('ix_user_role_role_id'), 'user_role', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_role_user_id'), 'user_role', ['user_id'], unique=False)
    op.create_table('verification_task',
    sa.Column('officer_id', sa.Uuid(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_task_officer_id'), 'verification_task', ['officer_id'], unique=False)
    op.create_index(op.f('ix_verification_task_target_id'), 'verification_task', ['target_id'], unique=False)
    op.create_table('cooperative',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('registration_no', sa.String(length=64), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cooperative_district_id'), 'cooperative', ['district_id'], unique=False)
    op.create_index(op.f('ix_cooperative_name'), 'cooperative', ['name'], unique=False)
    op.create_table('facility',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('facility_type', sa.String(length=32), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('verification_status', sa.String(length=16), nullable=False),
    sa.Column('cold_chain', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_location', 'facility', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_facility_district_id'), 'facility', ['district_id'], unique=False)
    op.create_index(op.f('ix_facility_name'), 'facility', ['name'], unique=False)
    op.create_table('intervention_priority',
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=4), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('gap_component', sa.Float(), nullable=True),
    sa.Column('vulnerability_component', sa.Float(), nullable=True),
    sa.Column('affected_scale_component', sa.Float(), nullable=True),
    sa.Column('readiness_component', sa.Float(), nullable=True),
    sa.Column('cost_component', sa.Float(), nullable=True),
    sa.Column('weight_config', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intervention_priority_crop_id'), 'intervention_priority', ['crop_id'], unique=False)
    op.create_index(op.f('ix_intervention_priority_district_id'), 'intervention_priority', ['district_id'], unique=False)
    op.create_index(op.f('ix_intervention_priority_year'), 'intervention_priority', ['year'], unique=False)
    op.create_table('market_price',
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('price_date', sa.Date(), nullable=True),
    sa.Column('price_rwf_per_kg', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_price_crop_id'), 'market_price', ['crop_id'], unique=False)
    op.create_index(op.f('ix_market_price_district_id'), 'market_price', ['district_id'], unique=False)
    op.create_table('official_indicator',
    sa.Column('indicator_code', sa.String(length=64), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('season', sa.String(length=4), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('uses_survey_weights', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_official_indicator_crop_id'), 'official_indicator', ['crop_id'], unique=False)
    op.create_index(op.f('ix_official_indicator_district_id'), 'official_indicator', ['district_id'], unique=False)
    op.create_index(op.f('ix_official_indicator_indicator_code'), 'official_indicator', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_official_indicator_year'), 'official_indicator', ['year'], unique=False)
    op.create_table('productivity_gap',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('observed_yield_kg_ha', sa.Float(), nullable=True),
    sa.Column('benchmark_yield_kg_ha', sa.Float(), nullable=True),
    sa.Column('gap_index', sa.Float(), nullable=True),
    sa.Column('benchmark_strategy', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_gap_crop_id'), 'productivity_gap', ['crop_id'], unique=False)
    op.create_index(op.f('ix_productivity_gap_district_id'), 'productivity_gap', ['district_id'], unique=False)
    op.create_index(op.f('ix_productivity_gap_season'), 'productivity_gap', ['season'], unique=False)
    op.create_index(op.f('ix_productivity_gap_year'), 'productivity_gap', ['year'], unique=False)
    op.create_table('productivity_metric',
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(length=4), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('cultivated_area_ha', sa.Float(), nullable=True),
    sa.Column('harvested_area_ha', sa.Float(), nullable=True),
    sa.Column('production_mt', sa.Float(), nullable=True),
    sa.Column('yield_kg_ha', sa.Float(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_productivity_metric_crop_id'), 'productivity_metric', ['crop_id'], unique=False)
    op.create_index(op.f('ix_productivity_metric_district_id'), 'productivity_metric', ['district_id'], unique=False)
    op.create_index(op.f('ix_productivity_metric_season'), 'productivity_metric', ['season'], unique=False)
    op.create_index(op.f('ix_productivity_metric_year'), 'productivity_metric', ['year'], unique=False)
    op.create_table('sector',
    sa.Column('code', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='MULTIPOLYGON', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_sector_geometry', 'sector', ['geometry'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_sector_code'), 'sector', ['code'], unique=True)
    op.create_index(op.f('ix_sector_district_id'), 'sector', ['district_id'], unique=False)
    op.create_index(op.f('ix_sector_name'), 'sector', ['name'], unique=False)
    op.create_table('facility_capacity_snapshot',
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('capacity_total_kg', sa.Float(), nullable=True),
    sa.Column('capacity_available_kg', sa.Float(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_facility_capacity_snapshot_crop_id'), 'facility_capacity_snapshot', ['crop_id'], unique=False)
    op.create_index(op.f('ix_facility_capacity_snapshot_facility_id'), 'facility_capacity_snapshot', ['facility_id'], unique=False)
    op.create_table('farmer_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('cooperative_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('consent_version', sa.String(length=32), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperative.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_profile_cooperative_id'), 'farmer_profile', ['cooperative_id'], unique=False)
    op.create_index(op.f('ix_farmer_profile_district_id'), 'farmer_profile', ['district_id'], unique=False)
    op.create_index(op.f('ix_farmer_profile_user_id'), 'farmer_profile', ['user_id'], unique=False)
    op.create_table('farm',
    sa.Column('farmer_id', sa.Uuid(), nullable=False),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('sector_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=160), nullable=True),
    sa.Column('area_ha', sa.Float(), nullable=True),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('gps_consent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ),
    sa.ForeignKeyConstraint(['sector_id'], ['sector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_farm_location', 'farm', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_farm_district_id'), 'farm', ['district_id'], unique=False)
    op.create_index(op.f('ix_farm_farmer_id'), 'farm', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farm_sector_id'), 'farm', ['sector_id'], unique=False)
    op.create_table('field_observation',
    sa.Column('officer_id', sa.Uuid(), nullable=True),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('observation_type', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_index(op.f('ix_field_observation_farm_id'), 'field_observation', ['farm_id'], unique=False)
    op.create_index(op.f('ix_field_observation_officer_id'), 'field_observation', ['officer_id'], unique=False)
    op.create_table('harvest_registration',
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('farmer_id', sa.Uuid(), nullable=True),
    sa.Column('district_id', sa.Uuid(), nullable=True),
    sa.Column('crop_id', sa.Uuid(), nullable=True),
    sa.Column('district_name', sa.String(length=64), nullable=True),
    sa.Column('crop_name', sa.String(length=64), nullable=True),
    sa.Column('expected_harvest_date', sa.Date(), nullable=True),
    sa.Column('expected_quantity_kg', sa.Float(), nullable=True),
    sa.Column('actual_quantity_kg', sa.Float(), nullable=True),
    sa.Column('client_uuid', sa.String(length=64), nullable=True),
    sa.Column('is_offline_created', sa.Boolean(), nullable=False),
    sa.Column('sync_status', sa.String(length=16), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['crop_id'], ['crop.id'], ),
    sa.ForeignKeyConstraint(['district_id'], ['district.id'], ),
    sa.ForeignKeyConstraint(['farm_id'], ['farm.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmer_profile.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_index(op.f('ix_harvest_registration_crop_id'), 'harvest_registration', ['crop_id'], unique=False)
    op.create_index(op.f('ix_harvest_registration_crop_name'), 'harvest_registration', ['crop_name'], unique=False)
    op.create_index(op.f('ix_harvest_registration_district_id'), 'harvest_registration', ['district_id'], unique=False)
    op.create_index(op.f('ix_harvest_registration_district_name'), 'harvest_registration', ['district_name'], unique=False)
    op.create_index(op.f('ix_harvest_registration_farm_id'), 'harvest_registration', ['farm_id'], unique=False)
    op.create_index(op.f('ix_harvest_registration_farmer_id'), 'harvest_registration', ['farmer_id'], unique=False)
    op.create_table('risk_score',
    sa.Column('harvest_id', sa.Uuid(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=True),
    sa.Column('band', sa.String(length=16), nullable=True),
    sa.Column('contributing_factors', sa.String(), nullable=True),
    sa.Column('recommended_actions', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('source_period', sa.String(), nullable=True),
    sa.Column('source_url', sa.String(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['harvest_id'], ['harvest_registration.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_score_harvest_id'), 'risk_score', ['harvest_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # spatial_ref_sys is intentionally NOT recreated here: it is owned by the
    # PostGIS extension. The extension itself is left installed, because other
    # objects in the database may depend on it.
    op.drop_index(op.f('ix_risk_score_harvest_id'), table_name='risk_score')
    op.drop_table('risk_score')
    op.drop_index(op.f('ix_harvest_registration_farmer_id'), table_name='harvest_registration')
    op.drop_index(op.f('ix_harvest_registration_farm_id'), table_name='harvest_registration')
    op.drop_index(op.f('ix_harvest_registration_district_name'), table_name='harvest_registration')
    op.drop_index(op.f('ix_harvest_registration_district_id'), table_name='harvest_registration')
    op.drop_index(op.f('ix_harvest_registration_crop_name'), table_name='harvest_registration')
    op.drop_index(op.f('ix_harvest_registration_crop_id'), table_name='harvest_registration')
    op.drop_table('harvest_registration')
    op.drop_index(op.f('ix_field_observation_officer_id'), table_name='field_observation')
    op.drop_index(op.f('ix_field_observation_farm_id'), table_name='field_observation')
    op.drop_table('field_observation')
    op.drop_index(op.f('ix_farm_sector_id'), table_name='farm')
    op.drop_index(op.f('ix_farm_farmer_id'), table_name='farm')
    op.drop_index(op.f('ix_farm_district_id'), table_name='farm')
    op.drop_index('idx_farm_location', table_name='farm', postgresql_using='gist')
    op.drop_table('farm')
    op.drop_index(op.f('ix_farmer_profile_user_id'), table_name='farmer_profile')
    op.drop_index(op.f('ix_farmer_profile_district_id'), table_name='farmer_profile')
    op.drop_index(op.f('ix_farmer_profile_cooperative_id'), table_name='farmer_profile')
    op.drop_table('farmer_profile')
    op.drop_index(op.f('ix_facility_capacity_snapshot_facility_id'), table_name='facility_capacity_snapshot')
    op.drop_index(op.f('ix_facility_capacity_snapshot_crop_id'), table_name='facility_capacity_snapshot')
    op.drop_table('facility_capacity_snapshot')
    op.drop_index(op.f('ix_sector_name'), table_name='sector')
    op.drop_index(op.f('ix_sector_district_id'), table_name='sector')
    op.drop_index(op.f('ix_sector_code'), table_name='sector')
    op.drop_index('idx_sector_geometry', table_name='sector', postgresql_using='gist')
    op.drop_table('sector')
    op.drop_index(op.f('ix_productivity_metric_year'), table_name='productivity_metric')
    op.drop_index(op.f('ix_productivity_metric_season'), table_name='productivity_metric')
    op.drop_index(op.f('ix_productivity_metric_district_id'), table_name='productivity_metric')
    op.drop_index(op.f('ix_productivity_metric_crop_id'), table_name='productivity_metric')
    op.drop_table('productivity_metric')
    op.drop_index(op.f('ix_productivity_gap_year'), table_name='productivity_gap')
    op.drop_index(op.f('ix_productivity_gap_season'), table_name='productivity_gap')
    op.drop_index(op.f('ix_productivity_gap_district_id'), table_name='productivity_gap')
    op.drop_index(op.f('ix_productivity_gap_crop_id'), table_name='productivity_gap')
    op.drop_table('productivity_gap')
    op.drop_index(op.f('ix_official_indicator_year'), table_name='official_indicator')
    op.drop_index(op.f('ix_official_indicator_indicator_code'), table_name='official_indicator')
    op.drop_index(op.f('ix_official_indicator_district_id'), table_name='official_indicator')
    op.drop_index(op.f('ix_official_indicator_crop_id'), table_name='official_indicator')
    op.drop_table('official_indicator')
    op.drop_index(op.f('ix_market_price_district_id'), table_name='market_price')
    op.drop_index(op.f('ix_market_price_crop_id'), table_name='market_price')
    op.drop_table('market_price')
    op.drop_index(op.f('ix_intervention_priority_year'), table_name='intervention_priority')
    op.drop_index(op.f('ix_intervention_priority_district_id'), table_name='intervention_priority')
    op.drop_index(op.f('ix_intervention_priority_crop_id'), table_name='intervention_priority')
    op.drop_table('intervention_priority')
    op.drop_index(op.f('ix_facility_name'), table_name='facility')
    op.drop_index(op.f('ix_facility_district_id'), table_name='facility')
    op.drop_index('idx_facility_location', table_name='facility', postgresql_using='gist')
    op.drop_table('facility')
    op.drop_index(op.f('ix_cooperative_name'), table_name='cooperative')
    op.drop_index(op.f('ix_cooperative_district_id'), table_name='cooperative')
    op.drop_table('cooperative')
    op.drop_index(op.f('ix_verification_task_target_id'), table_name='verification_task')
    op.drop_index(op.f('ix_verification_task_officer_id'), table_name='verification_task')
    op.drop_table('verification_task')
    op.drop_index(op.f('ix_user_role_user_id'), table_name='user_role')
    op.drop_index(op.f('ix_user_role_role_id'), table_name='user_role')
    op.drop_table('user_role')
    op.drop_index(op.f('ix_sync_event_user_id'), table_name='sync_event')
    op.drop_index(op.f('ix_sync_event_client_uuid'), table_name='sync_event')
    op.drop_table('sync_event')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_district_province_id'), table_name='district')
    op.drop_index(op.f('ix_district_name'), table_name='district')
    op.drop_index(op.f('ix_district_code'), table_name='district')
    op.drop_index('idx_district_geometry', table_name='district', postgresql_using='gist')
    op.drop_table('district')
    op.drop_index(op.f('ix_audit_log_actor_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_role_name'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_recommendation_target_id'), table_name='recommendation')
    op.drop_table('recommendation')
    op.drop_index(op.f('ix_province_code'), table_name='province')
    op.drop_table('province')
    op.drop_index(op.f('ix_model_version_name'), table_name='model_version')
    op.drop_table('model_version')
    op.drop_index(op.f('ix_data_source_source_id'), table_name='data_source')
    op.drop_table('data_source')
    op.drop_index(op.f('ix_crop_name'), table_name='crop')
    op.drop_index(op.f('ix_crop_code'), table_name='crop')
    op.drop_table('crop')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
